Feature: Indents
vaadin/vaadin-rich-text-editor pull request #146
Opened 2020-07-20 11:51 UTC by niiyeboah

Closes #140

2020-09-08 16:47 UTC, niiyeboah commented
The temp icons are on my [Figma](https://www.figma.com/file/fmGrfdOLyOwdkQdybZ0Vly/Indent-Icons?node-id=0%3A1).

2020-09-21 10:09 UTC, yuriy-fix requested changes
Do we have some specifications for the expected keyboard hotkeys for indentations? 🤔 
For me it's a bit unexpected that <kbd>Tab</kbd> applies indent styles in `lists`, but in i.e. paragraphs it's adding `\t` 😅 
It's also not obvious that decreasing of the indentation should be done with <kbd>Backspace</kbd>. Personally I have moved the focus to the toolbar ~10 times with <kbd>Shift</kbd> + <kbd>Tab</kbd> while testing instead of changing the indentation.

2020-09-21 14:21 UTC, rolfsmeds commented
> Do we have some specifications for the expected keyboard hotkeys for indentations? 🤔
> For me it's a bit unexpected that Tab applies indent styles in `lists`, but in i.e. paragraphs it's adding `\t` 😅
> It's also not obvious that decreasing of the indentation should be done with Backspace. Personally I have moved the focus to the toolbar ~10 times with Shift + Tab while testing instead of changing the indentation.

This has not been explicitly discussed, and as such, my expectation is that it should work as in standard Quill, which seems to be just like most rich text editors out there:
- Tab key adds \t in paragraphs and indents lists.
- BOTH Shift-Tab AND backspace remove \t and unindent lists.

If there are platform-specific reasons to deviate from these, we need to discuss.

2020-09-21 14:30 UTC, rolfsmeds commented on src/vaadin-rich-text-editor-content-styles.html
> +      :host(:not([dir="rtl"])) .ql-editor .ql-indent-9 {
No limitation has been specified. Is Quill somehow limited to 8?

2020-09-21 14:33 UTC, rolfsmeds commented on src/vaadin-rich-text-editor.html
> +          content = this._convertLists(content);
Yes, nested lists are expected to work correctly.

2020-09-21 14:50 UTC, niiyeboah commented on src/vaadin-rich-text-editor-toolbar-styles.html
> -      [part~="toolbar-button-undo"]::before,
Do these styles get used? When I was testing it seemed that the icons were coming from lumo-styles or material-styles

2020-09-21 14:51 UTC, niiyeboah commented on src/vaadin-rich-text-editor-toolbar-styles.html
> -      [part~="toolbar-button-undo"]::before,
I can put them back, but it seemed like they were unnecessary

2020-09-22 07:07 UTC, yuriy-fix commented on src/vaadin-rich-text-editor-content-styles.html
> +      :host(:not([dir="rtl"])) .ql-editor .ql-indent-9 {
As discussed with @rolfsmeds, I guess for this particular case we can go with the limitation to `ql-indent-8` as Quill does it.
P.S. So `ql-indent-9` can be removed.

2020-09-22 07:10 UTC, yuriy-fix commented
> This has not been explicitly discussed, and as such, my expectation is that it should work as in standard Quill, which seems to be just like most rich text editors out there:
> 
> * Tab key adds \t in paragraphs and indents lists.
> * BOTH Shift-Tab AND backspace remove \t and unindent lists.
> 
> If there are platform-specific reasons to deviate from these, we need to discuss.

As discussed with @rolfsmeds, for this case we can go with behavioral altering change, so that <kbd>Shift</kbd> + <kbd>Tab</kbd> won't anymore move focus back to the toolbar and <kbd>Esc</kbd> will do that instead. So <kbd>Shift</kbd> + <kbd>Tab</kbd> will now remove \t and unindent lists (as well as <kbd>Backspace</kbd>)

2020-09-30 12:09 UTC, web-padawan commented on src/vaadin-rich-text-editor.html
> +            const endTag = `-end-${type}-`;
This only allows nesting lists of the same, i.e. not possible to nest `<ul>` lists inside `<ol>` and vice versa.

The problem is how we detect which type of list does the `<li>` element belong to. 
Quill master branch uses `li[data-list=ordered]` and `li[data-list=bullet]`, maybe we could do the same.

Then we would need to take that into account when converting lists.

2020-09-30 12:20 UTC, web-padawan commented on src/vaadin-rich-text-editor.html
> +            const endTag = `-end-${type}-`;
Another thing that I noticed at Quill master branch is that they [always use `<ol>`](https://github.com/quilljs/quill/blob/e9f628b5562e78126291bb25f63d0dfc3f6c6f86/formats/list.js#L7) tag.

Then the markup for the bullet lists looks like this:

```html
<ol>
  <li data-list="ordered">0123</li>
  <li data-list="ordered">5678</li>
</ol>
```

I'm not sure if upgrading Quill to 2.0 would make this feature easier to implement or not.

2021-08-19 10:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/vaadin-rich-text-editor?pullRequest=146) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/vaadin-rich-text-editor?pullRequest=146) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/vaadin-rich-text-editor?pullRequest=146) it.</sub>

2022-05-24 10:57 UTC, yuriy-fix commented
Closing as stale.

2022-05-24 10:57 UTC, closed without merging